Update root check

diff --git a/update-fedora b/update-fedora
--- a/update-fedora
+++ b/update-fedora
@@ -1,5 +1,12 @@
 #!/bin/bash
 # Script to update Fedora systems
+# Ensure the script is run with root privileges
+
+if [ "$(id -u)" != "0" ];
+then
+   echo "This script must be run as root. Try 'sudo update-fedora'" 1>&2
+   exit 1
+fi
 
 # Distribution checks
 distroCheckOne=`cat /etc/os-release | grep -i "NAME=\"Fedora Linux\""`
@@ -12,9 +19,10 @@ then
 fi
 
 echo 'Performing system update'
-sudo dnf clean all
-sudo dnf offline clean
-sudo dnf --refresh upgrade --offline -y
+
+dnf clean all
+dnf offline clean
+dnf --refresh offline-upgrade -y
 
 if command -v flatpak &> /dev/null
 then
@@ -25,7 +33,12 @@ fi
 if command -v akmods &> /dev/null
 then            
     echo 'Rebuilding akmods, please wait'
-    sudo akmods
+    akmods
 fi
-
-sudo dnf offline reboot
+echo "--- Checking if reboot is required ---"
+if needs-restarting -r > /dev/null; then
+    echo "System is up to date. No reboot required."
+else
+    echo "Reboot required to complete updates."
+    dnf offline reboot
+fi
